"""Схема sbavito: прайс, промпты, база знаний, диалоги, лиды.

Сама схема создаётся в `migrations/env.py` (до таблицы версий Alembic),
здесь — её содержимое.

Ревизия: 7cac61ed44d2
Предыдущая:
Создана: 2026-07-22 15:12:40.691637+03:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7cac61ed44d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Enum'ы Alembic создаёт сам при create_table, но НЕ удаляет при drop_table.
# Без явного DROP TYPE повторный `upgrade` после `downgrade` падает на
# «type already exists» — снимаем их вручную в downgrade.
TIPY = ('account_kind', 'availability', 'price_unit', 'message_role', 'lead_status')


def upgrade() -> None:
    # Триграммы нужны индексам gin_trgm_ops ниже: без расширения миграция
    # упадёт на чистой машине (в общем postgres16 оно уже стоит).
    op.execute('create extension if not exists pg_trgm')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('goods', 'services', name='account_kind', schema='sbavito'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('code', name=op.f('uq_accounts_code')),
    schema='sbavito'
    )
    op.create_table('prompt_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_base')),
    schema='sbavito'
    )
    op.create_table('account_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('persona', sa.String(length=128), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sbavito.accounts.id'], name=op.f('fk_account_prompts_account_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_prompts')),
    schema='sbavito'
    )
    op.create_index('ix_account_prompts_account', 'account_prompts', ['account_id'], unique=False, schema='sbavito')
    op.create_table('dialogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('chat_key', sa.String(length=128), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('client_username', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sbavito.accounts.id'], name=op.f('fk_dialogs_account_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dialogs')),
    sa.UniqueConstraint('account_id', 'channel', 'chat_key', name='uq_dialogs_chat'),
    schema='sbavito'
    )
    op.create_index('ix_dialogs_last_message_at', 'dialogs', ['last_message_at'], unique=False, schema='sbavito')
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sbavito.accounts.id'], name=op.f('fk_faq_account_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq')),
    schema='sbavito'
    )
    op.create_index('ix_faq_account', 'faq', ['account_id'], unique=False, schema='sbavito')
    op.create_table('knowledge_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sbavito.accounts.id'], name=op.f('fk_knowledge_blocks_account_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_blocks')),
    sa.UniqueConstraint('account_id', 'key', name='uq_knowledge_blocks_account_key'),
    schema='sbavito'
    )
    op.create_table('price_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('price_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inserted', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deactivated', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sbavito.accounts.id'], name=op.f('fk_price_meta_account_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_meta')),
    schema='sbavito'
    )
    op.create_index('ix_price_meta_account', 'price_meta', ['account_id'], unique=False, schema='sbavito')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=True),
    sa.Column('grade', sa.String(length=32), nullable=True),
    sa.Column('species', sa.String(length=32), nullable=True),
    sa.Column('length_m', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('working_width_mm', sa.Integer(), nullable=True),
    sa.Column('unit', sa.Enum('piece', 'linear_m', name='price_unit', schema='sbavito'), server_default=sa.text("'piece'"), nullable=False),
    sa.Column('price_apiece', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_per_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_package', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('availability', sa.Enum('in_stock', 'out', 'unknown', name='availability', schema='sbavito'), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('characteristics', sa.Text(), nullable=True),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sbavito.accounts.id'], name=op.f('fk_products_account_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('account_id', 'article', name='uq_products_account_article'),
    schema='sbavito'
    )
    op.create_index('ix_products_account', 'products', ['account_id'], unique=False, schema='sbavito')
    op.create_index('ix_products_family', 'products', ['family'], unique=False, schema='sbavito')
    op.create_index('ix_products_name_trgm', 'products', ['name'], unique=False, schema='sbavito', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'sent', 'failed', name='lead_status', schema='sbavito'), server_default=sa.text("'new'"), nullable=False),
    sa.Column('amo_contact_id', sa.BigInteger(), nullable=True),
    sa.Column('amo_lead_id', sa.BigInteger(), nullable=True),
    sa.Column('amo_responsible_id', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['sbavito.accounts.id'], name=op.f('fk_leads_account_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dialog_id'], ['sbavito.dialogs.id'], name=op.f('fk_leads_dialog_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    schema='sbavito'
    )
    op.create_index('ix_leads_account_created', 'leads', ['account_id', 'created_at'], unique=False, schema='sbavito')
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False, schema='sbavito')
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('client', 'bot', 'system', 'tool', name='message_role', schema='sbavito'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dialog_id'], ['sbavito.dialogs.id'], name=op.f('fk_messages_dialog_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    schema='sbavito'
    )
    op.create_index('ix_messages_dialog_created', 'messages', ['dialog_id', 'created_at'], unique=False, schema='sbavito')
    op.create_table('product_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['sbavito.products.id'], name=op.f('fk_product_aliases_product_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_aliases')),
    sa.UniqueConstraint('product_id', 'alias', name='uq_product_aliases_product_alias'),
    schema='sbavito'
    )
    op.create_index('ix_product_aliases_alias_trgm', 'product_aliases', ['alias'], unique=False, schema='sbavito', postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_aliases_alias_trgm', table_name='product_aliases', schema='sbavito', postgresql_using='gin')
    op.drop_table('product_aliases', schema='sbavito')
    op.drop_index('ix_messages_dialog_created', table_name='messages', schema='sbavito')
    op.drop_table('messages', schema='sbavito')
    op.drop_index('ix_leads_status', table_name='leads', schema='sbavito')
    op.drop_index('ix_leads_account_created', table_name='leads', schema='sbavito')
    op.drop_table('leads', schema='sbavito')
    op.drop_index('ix_products_name_trgm', table_name='products', schema='sbavito', postgresql_using='gin')
    op.drop_index('ix_products_family', table_name='products', schema='sbavito')
    op.drop_index('ix_products_account', table_name='products', schema='sbavito')
    op.drop_table('products', schema='sbavito')
    op.drop_index('ix_price_meta_account', table_name='price_meta', schema='sbavito')
    op.drop_table('price_meta', schema='sbavito')
    op.drop_table('knowledge_blocks', schema='sbavito')
    op.drop_index('ix_faq_account', table_name='faq', schema='sbavito')
    op.drop_table('faq', schema='sbavito')
    op.drop_index('ix_dialogs_last_message_at', table_name='dialogs', schema='sbavito')
    op.drop_table('dialogs', schema='sbavito')
    op.drop_index('ix_account_prompts_account', table_name='account_prompts', schema='sbavito')
    op.drop_table('account_prompts', schema='sbavito')
    op.drop_table('prompt_base', schema='sbavito')
    op.drop_table('accounts', schema='sbavito')
    # ### end Alembic commands ###

    for tip in TIPY:
        op.execute(f'drop type if exists sbavito.{tip}')
